package HibernateShopping;
// Generated 2012-jan-03 13:52:28 by Hibernate Tools 3.2.1.GA



/**
 * MusicTracks generated by hbm2java
 */
public class MusicTracks  implements java.io.Serializable {


     private int id;
     private Integer recordingId;
     private String title;
     private Integer duration;

    public MusicTracks() {
    }

	
    public MusicTracks(int id) {
        this.id = id;
    }
    public MusicTracks(int id, Integer recordingId, String title, Integer duration) {
       this.id = id;
       this.recordingId = recordingId;
       this.title = title;
       this.duration = duration;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getRecordingId() {
        return this.recordingId;
    }
    
    public void setRecordingId(Integer recordingId) {
        this.recordingId = recordingId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }




}


