package HibernateShopping;
// Generated 2012-jan-04 23:15:20 by Hibernate Tools 3.2.1.GA

import javax.persistence.Id;




/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     @Id private Integer userId;
     private String userName;
     private String userPass;
     private String firstname;
     private String lastname;
     private String streetaddress;
     private String zip;
     private String city;
     private String country;
     private String email;

    public Users() {
    }

	
    public Users(String userName, String userPass) {
        this.userName = userName;
        this.userPass = userPass;
    }
    public Users(String userName, String userPass, String firstname, String lastname, String streetaddress, String zip, String city, String country, String email) {
       this.userName = userName;
       this.userPass = userPass;
       this.firstname = firstname;
       this.lastname = lastname;
       this.streetaddress = streetaddress;
       this.zip = zip;
       this.city = city;
       this.country = country;
       this.email = email;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getStreetaddress() {
        return this.streetaddress;
    }
    
    public void setStreetaddress(String streetaddress) {
        this.streetaddress = streetaddress;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


